services:
  frontend:
    build:
      context: ./beer-rating-client-vue
      dockerfile: Dockerfile
    ports:
      - "${BEER_FRONTEND_PORT:-9570}:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
      - TZ=Europe/Stockholm
    restart: unless-stopped
    container_name: Beer-rating-client
    networks:
      - beer-network
    env_file:
      - ./beer-rating-client-vue/.env
    depends_on:
      - backend
  backend:
    build:
      context: ./beer-rating-service
      dockerfile: Dockerfile
    ports:
      - "${BEER_BACKEND_PORT:-9571}:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/echo || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
    container_name: Beer-rating-service
    networks:
      - beer-network
    env_file:
      - ./beer-rating-service/.env

networks:
  beer-network:
    driver: bridge
