### Define variables
@host = http://localhost:{{$dotenv PORT}}
@username = john_doe
@password = SecurePass123!
@token = {{postLogin.response.body.token}}
@beerId = {{postBeer.response.body._id}}

### Register a new user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Login as the user
# @name postLogin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Create a new beer
# @name postBeer
# This request requires a valid JWT token.
POST {{host}}/api/beers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Guinness",
  "type": "Stout"
}

### Get all beers
GET {{host}}/api/beers

### Get a specific beer with ratings
GET {{host}}/api/beers/{{beerId}}

### Add a rating to a beer
POST {{host}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "beerId": "{{beerId}}",
  "score": 4,
  "comment": "A very smooth and flavorful stout."
}

### Try to add another rating to the same beer by the same user (should fail)
POST {{host}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "beerId": "{{beerId}}",
  "score": 5,
  "comment": "Absolutely loved it!"
}

### Fetch beers from google sheets
GET {{host}}/api/sheets/beers-from-sheet

### Clear sheets cache
POST {{host}}/api/sheets/clear-cache
Content-Type: application/json

{
  "cacheName": "beers"
}

### Get beer by type/style
GET {{host}}/api/beers/type/Stout2

### Update a Beer
PUT {{host}}/api/beers/{{beerId}}
Content-Type: application/json

{
  "name": "Updated Beer Name",
  "type": "IPA",
  "brewery": "Updated Brewery",
  "abv": 5.5
}

### Delete a Beer
DELETE {{host}}/api/beers/{{beerId}}


@ratingId = 66cc891fdd1c48e27c4bfffa
### Update a Rating
PUT {{host}}/api/ratings/{{beerId}}/ratings/{{ratingId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "score": 4,
  "comment": "Updated comment"
}

### Delete a Rating
DELETE {{host}}/api/ratings/{{beerId}}/ratings/{{ratingId}}
Authorization: Bearer {{token}} 