### Define variables
@host = http://localhost:{{$dotenv PORT}}
#@username = johh_viewer
#@username = john_admin
@username = john_user
@password = SecurePass123!
@token = {{postLogin.response.body.token}}
#@beerId = {{postBeer.response.body._id}}
@beerId = 66cdc28f7b8d73fb33594f0b
@page=1
@limit=20

### Register a new user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Login as the user
# @name postLogin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Create a new beer
# @name postBeer
# This request requires a valid JWT token.
POST {{host}}/api/beers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Guinness",
  "type": "Stout"
}

### Get all beers with pagination
GET {{host}}/api/beers?page={{page}}&limit={{limit}}

### Get all beers of multiple styles
GET {{host}}/api/beers?styles=Lager,IPA&limit={{limit}}&page={{page}}


### Get a specific beer with ratings
GET {{host}}/api/beers/{{beerId}}

### Add a rating to a beer
POST {{host}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "beerId": "{{beerId}}",
  "score": 4,
  "comment": "A very smooth and flavorful stout."
}

### Try to add another rating to the same beer by the same user (should fail)
POST {{host}}/api/ratings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "beerId": "{{beerId}}",
  "score": 5,
  "comment": "Absolutely loved it!"
}

### Fetch beers from google sheets
GET {{host}}/api/sheets/beers-from-sheet

### Clear sheets cache
POST {{host}}/api/sheets/clear-cache
Content-Type: application/json

{
  "cacheName": "beers"
}

### Get beer by type/style
GET {{host}}/api/beers/type/Stout2?page={{page}}&limit={{limit}}

### Update a Beer
PUT {{host}}/api/beers/{{beerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Beer Name",
  "type": "IPA",
  "brewery": "Updated Brewery",
  "abv": 5.5
}

### Delete a Beer
DELETE {{host}}/api/beers/{{beerId}}
Authorization: Bearer {{token}}


@ratingId = 66cf0dd20303f0cba812e141
### Update a Rating
PUT {{host}}/api/ratings/{{ratingId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "score": 3,
  "comment": "Updated comment1"
}

### Delete a Rating
DELETE {{host}}/api/ratings/{{ratingId}}
Authorization: Bearer {{token}} 